export const AUTH_COPY = {
  signIn: "Sign in",
  signInSubtitle: "Enter the email and password from setup.",
  enterShop: "Enter shop",
  forgotPassword: "Forgot password?",
  forgotPasswordSoon: "Password reset is coming soon.",
  firstTime: "First time?",
  setUpShop: "Set up the shop",
  alreadySetUp: "Already set up?",
  setupTitle: "Set up your shop",
  setupSubtitle: "Name the shop, create the owner login, and set slip branding.",
  createShop: "Create shop",
  confirmPassword: "Confirm password",
  passwordMismatch: "Passwords do not match",
  passwordMin: "Use at least 6 characters",
  tagline: "Tagline",
  taglineHint: "Printed under the shop name on receipts",
  contactLine: "Contact line",
  contactLineHint: "Phone or WhatsApp on receipts",
  showLogo: "Show logo on receipts",
  username: "Username",
  email: "Email",
  invalidCredentials: "Email or password is wrong",
  setupFailed: "Could not complete setup",
  sessionExpired: "Session expired. Sign in again.",
  signingOut: "Signed out",
} as const;
