export const routes = {
  setup: "/setup",
  login: "/login",
  dashboard: "/",
  pos: "/pos",
  sales: "/sales",
  invoices: "/invoices",
  credit: "/credit",
  returns: "/returns",
  salesReturns: "/sales/returns",
  salesClaims: "/sales/claims",
  salesProducts: "/sales/products",
  products: "/products",
  productsSold: "/products/sold",
  productsClaims: "/products/claims",
  productsLow: "/products/low",
  stock: "/products/stock",
  lots: "/products/lots",
  categories: "/categories",
  productsCategories: "/products/categories",
  units: "/products/units",
  transfers: "/products/transfers",
  reorder: "/reorder",
  suppliers: "/suppliers",
  customers: "/customers",
  employees: "/employees",
  production: "/production",
  repair: "/repair",
  expenses: "/expenses",
  transactions: "/transactions",
  shops: "/shops",
  reports: "/reports",
  analytics: "/analytics",
  settings: "/settings",
  settingsReceipt: "/settings/receipt",
  settingsProducts: "/settings/products",
  settingsLocalization: "/settings/localization",
  settingsPrinter: "/settings/printer",
  settingsDevices: "/settings/devices",
  settingsSync: "/settings/sync",
} as const;

export type AppRoute = (typeof routes)[keyof typeof routes];
