export const routes = {
  setup: "/setup",
  login: "/login",
  dashboard: "/",
  pos: "/pos",
  invoices: "/invoices",
  credit: "/credit",
  returns: "/returns",
  products: "/products",
  stock: "/stock",
  lots: "/lots",
  categories: "/categories",
  units: "/units",
  transfers: "/transfers",
  reorder: "/reorder",
  suppliers: "/suppliers",
  customers: "/customers",
  employees: "/employees",
  production: "/production",
  repair: "/repair",
  expenses: "/expenses",
  transactions: "/transactions",
  shops: "/shops",
  reports: "/reports",
  analytics: "/analytics",
  settings: "/settings",
} as const;

export type AppRoute = (typeof routes)[keyof typeof routes];
